In [64]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
from othello.OthelloGame import OthelloGame as Game
from othello.OthelloGame import display as displayGame
from othello_viz import display_board
from matplotlib import pyplot as plt

In [51]:
game.getValidMoves(board, player)[1]

0

In [52]:
game.getGameEnded(board, player)

0

In [102]:
%matplotlib widget
# Defino juego
n = 4
game = Game(n)
board = game.getInitBoard()
player = 1

f, ax = plt.subplots(1, 1, figsize = (3, 3))
f.patch.set_facecolor('lightgray')
display_board(game, board, player_turn= player, valid_moves = None, figsize = (3, 3), ax = ax)
text=ax.text(-1,-1, "", va="bottom", ha="left")

def onclick(event):
    global game, board, player
    x = int(event.xdata + 0.5)
    y = int(event.ydata + 0.5)
    action = x + (3-y)*4
    tx = 'action=%d, xdata=%f, ydata=%f' % (action, x, y)
    #vtext.set_text(str(player))
    if game.getValidMoves(board, player)[action] == 1:
        board, player = game.getNextState(board, player, action)
        display_board(game, board, player_turn= player, valid_moves = None, figsize = (3, 3), ax = ax)
        text.set_text('')
        ended = game.getGameEnded(board, player)
        if not ended and game.getValidMoves(board, player)[16] == 1:
            board, player = game.getNextState(board, player, 16)
            display_board(game, board, player_turn= player, valid_moves = None, figsize = (3, 3), ax = ax)
    else:
        # tx = 'action=%d, xdata=%f, ydata=%f' % (action, x, y)
        text.set_text('Invalid move')

cid = f.canvas.mpl_connect('button_press_event', onclick)

plt.show()

FigureCanvasNbAgg()

In [66]:
from othello_jupyter_play import Play_Othello

In [194]:
%matplotlib widget
# Defino juego
play_othello = Play_Othello(n=4, first_player=1)

FigureCanvasNbAgg()

In [137]:
game.getGameEnded(board, 1)

0

In [212]:
import numpy as np
board = np.array([[ -1,  -1,  -1,  -1],
       [ -1,  1,  -1,  0],
       [ -1,  -1, -1,  -1],
       [ 0,  0,  0,  0]])

In [213]:
board

array([[-1, -1, -1, -1],
       [-1,  1, -1,  0],
       [-1, -1, -1, -1],
       [ 0,  0,  0,  0]])

In [214]:
game.getGameEnded(board, -1)

0

In [215]:
game.getValidMoves(board, 1)

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0])

In [245]:
%matplotlib widget
play_othello = Play_Othello(n=6, first_player=1)

FigureCanvasNbAgg()

In [224]:
game = Game(6)
game.getInitBoard()

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  1,  0,  0],
       [ 0,  0,  1, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [ ]:
game.get