In [5]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [6]:
from othello.OthelloGame import OthelloGame as Game
from othello.OthelloGame import display as displayGame
from matplotlib import pyplot as plt
from matplotlib import patches
import numpy as np

In [7]:
class dotdict(dict):
    def __getattr__(self, name):
        return self[name]

In [8]:
from MCTS import MCTS

In [9]:
class RandomPlayer():
    def __init__(self, game):
        self.game = game
        
    def predict(self, canonicalBoard):
        valid_modes = self.game.getValidMoves(board, 1)
        valid_modes = valid_modes/valid_modes.sum()
        return  valid_modes, game.getGameEnded(board, 1)

In [10]:
n = 4
game = Game(n)
board = game.getInitBoard()
nnet = RandomPlayer(game)

In [11]:
board = np.array([[ 0,  0,  0,  0],
       [ 0, -1,  1,  0],
       [ 0,  1, -1,  0],
       [ 0,  0,  0,  0]])

In [12]:
board = np.array(
    [[ 1,  -1,  -1,  1],
    [ -1, -1,  1,  1],
    [ 1,  1, -1,  1],
    [ 1,  -1,  0,  0]])

In [13]:
board

array([[ 1, -1, -1,  1],
       [-1, -1,  1,  1],
       [ 1,  1, -1,  1],
       [ 1, -1,  0,  0]])

In [14]:
args = dotdict({
    'numMCTSSims': 1000, # Cantidad de simulaciones de MC
    'cpuct': 1
})
mcts = MCTS(game, nnet, args)

In [15]:
ps = mcts.getActionProb(board)

In [16]:
for board_str, v in mcts.Qsa:
    b = np.frombuffer(board_str, dtype=int).reshape(game.n, game.n)
    print(b, v)
    print(mcts.Qsa[(board_str, v)])

[[ 1 -1 -1  1]
 [-1 -1  1  1]
 [ 1  1 -1  1]
 [ 1 -1  0  0]] 14
0.9989858012170385
[[ 1 -1 -1  1]
 [-1 -1  1  1]
 [ 1  1 -1  1]
 [ 1 -1  0  0]] 15
-0.1846153846153846
[[-1  1  1 -1]
 [ 1  1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1  0]] 15
-1.0
[[-1  1  1 -1]
 [ 1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1  0 -1]] 14
0.19999999999999998
