# BFS

In [11]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [12]:
from numba import jit

In [13]:
from othello.OthelloGame import OthelloGame as Game
from othello.OthelloGame import display as displayGame
from matplotlib import pyplot as plt
from matplotlib import patches
import numpy as np
from tree_search_algs import bfs_depth, bfs_cannonical, bfs_no_depth

In [4]:
n = 4
game = Game(n)
board = game.getInitBoard()

In [5]:
%time states_depth = bfs_depth(game, board, verbose=1)

Profundidad: 1
Estados hasta el momento: 1
Time: 0.0
Profundidad: 2
Estados hasta el momento: 5
Time: 0.0
Profundidad: 3
Estados hasta el momento: 17
Time: 0.0
Profundidad: 4
Estados hasta el momento: 59
Time: 0.0
Profundidad: 5
Estados hasta el momento: 179
Time: 0.03
Profundidad: 6
Estados hasta el momento: 555
Time: 0.09
Profundidad: 7
Estados hasta el momento: 1603
Time: 0.29
Profundidad: 8
Estados hasta el momento: 4121
Time: 0.68
Profundidad: 9
Estados hasta el momento: 9769
Time: 1.64
Profundidad: 10
Estados hasta el momento: 19487
Time: 2.81
Profundidad: 11
Estados hasta el momento: 32295
Time: 4.23
Profundidad: 12
Estados hasta el momento: 43195
Time: 4.4
Profundidad: 13
Estados hasta el momento: 46317
Time: 4.01
Profundidad: 14
Estados hasta el momento: 46673
Time: 1.64
Profundidad: 15
Estados hasta el momento: 46689
Time: 0.15
Profundidad: 16
Estados hasta el momento: 46689
Time: 0.0
Profundidad: 17
Estados hasta el momento: 46689
Time: 0.0
CPU times: user 20.3 s, sys: 646 m

In [6]:
%time states_no_depth = bfs_no_depth(game, board)

CPU times: user 19.4 s, sys: 300 ms, total: 19.7 s
Wall time: 19.3 s


In [9]:
%time states_cannonical = bfs_cannonical(game, board)

CPU times: user 28.5 s, sys: 240 ms, total: 28.7 s
Wall time: 28.4 s


In [10]:
len(states_depth), len(set(states_no_depth)), len(states_cannonical)

(46689, 58533, 53651)

# 6x6

In [33]:
n = 4
game = Game(n)
board = game.getInitBoard()

In [49]:
directions = np.array([(1,1),(1,0),(1,-1),(0,-1),(-1,-1),(-1,0),(-1,1),(0,1)])

In [50]:
np.array(directions)

array([[ 1,  1],
       [ 1,  0],
       [ 1, -1],
       [ 0, -1],
       [-1, -1],
       [-1,  0],
       [-1,  1],
       [ 0,  1]])

array([False, False, False, False, False, False, False, False])

In [83]:
step

array([[ 10211.,  10211.],
       [ 10211.,      0.],
       [ 10211., -10211.],
       [     0., -10211.],
       [-10211., -10211.],
       [-10211.,      0.],
       [-10211.,  10211.],
       [     0.,  10211.]])

In [87]:
n = board.shape[0]
x = 0
y = 0
ones_array = np.ones([2, 8]).T
step = ones_array * np.array([x, y])

while ((step[:,0]>=0) * (step[:,0]<n) * (step[:,1]>=0) * (step[:,1]<n)).sum() > 0:
    step = step + directions

In [46]:

for y in range(n):
    for x in range(n):
        if board[x, y] == 1:
            for dx in 
        print(board[x, y])

0
0
0
0
0
-1
1
0
0
1
-1
0
0
0
0
0


In [39]:
def get_legal_moves(board, player):
    """Returns all the legal moves for the given color.
    (1 for white, -1 for black
    """
    n = board.shape[0]
    moves = set()  # stores the legal moves.

    # Get all the squares with pieces of the given color.
    for y in range(n):
        for x in range(n):
            if board[x][y]==color:
                newmoves = self.get_moves_for_square((x,y))
                moves.update(newmoves)
    return list(moves)

def getGameEnded(self, board, player):
    # return 0 if not ended, 1 if player 1 won, -1 if player 1 lost
    # player = 1
    b = Board(self.n)
    b.pieces = np.copy(board)
    if b.has_legal_moves(player):
        return 0
    if b.has_legal_moves(-player):
        return 0
    diff = b.countDiff(player)
    if diff > 0:
        return 1
    elif diff < 0:
        return -1
    # draw case
    return -0.2

In [34]:
def bfs_depth(game, root, verbose=0):
    n = root.shape[0]
    root_str = tuple(root.reshape(-1))
    depth = 0
    seen = set([(root_str, np.power(-1, depth))])
    cannonical_states = {}
    # deque es como una pila pero con doble entrada (rear-front)
    queue = collections.deque([root_str, 'level_end'])
    player = 1
    time0 = time.time()
    while queue:
        vertex = queue.popleft()
        if vertex == 'level_end':
            depth = depth + 1
            player = np.power(-1, depth)
            queue.append('level_end')
            vertex = queue.popleft()   
            if verbose == 1:
                print('Profundidad:', depth)
                print('Estados hasta el momento:', len(cannonical_states))
                time1 = time.time()
                print('Time:', int((time1 - time0) * 100)/100)
                time0 = time1
            if vertex == 'level_end':
                break
        state = np.array(vertex).reshape(n, n)
        valid_moves = np.array(game.getValidMoves(state, player))
        valid_moves = np.where(valid_moves == 1)[0]
        if game.getGameEnded(state, player) == 0:
            cannonical_states[vertex] = {}
            for action in valid_moves:
                cannonical_states[vertex][action] = {}
                next_state, _ = game.getNextState(state, player, action)
                node = tuple(next_state.reshape(-1))
                if (node, player) not in seen:
                    cannonical_states[vertex][action]['next_node'] = node*player
                    seen.add((node, player))
                    queue.append(node)
    return cannonical_states

In [35]:
%time x = bfs_depth(game, board, verbose=1)

Profundidad: 1
Estados hasta el momento: 1
Time: 0.0
Profundidad: 2
Estados hasta el momento: 5
Time: 0.0
Profundidad: 3
Estados hasta el momento: 17
Time: 0.0
Profundidad: 4
Estados hasta el momento: 59
Time: 0.0
Profundidad: 5
Estados hasta el momento: 179
Time: 0.03
Profundidad: 6
Estados hasta el momento: 555
Time: 0.09
Profundidad: 7
Estados hasta el momento: 1603
Time: 0.29
Profundidad: 8
Estados hasta el momento: 4121
Time: 0.65
Profundidad: 9
Estados hasta el momento: 9769
Time: 1.59
Profundidad: 10
Estados hasta el momento: 19487
Time: 2.76
Profundidad: 11
Estados hasta el momento: 32295
Time: 4.17
Profundidad: 12
Estados hasta el momento: 43195
Time: 4.46
Profundidad: 13
Estados hasta el momento: 46317
Time: 4.04
Profundidad: 14
Estados hasta el momento: 46673
Time: 1.57
Profundidad: 15
Estados hasta el momento: 46689
Time: 0.15
Profundidad: 16
Estados hasta el momento: 46689
Time: 0.01
Profundidad: 17
Estados hasta el momento: 46689
Time: 0.0
CPU times: user 20.1 s, sys: 457