In [1]:
%load_ext autoreload
%autoreload 2

# Dynamic Programming

In [2]:
from othello.OthelloGame import OthelloGame as Game
from othello.OthelloGame import display as displayGame
from matplotlib import pyplot as plt
from matplotlib import patches
import numpy as np
from tree_search_algs import bfs_cannonical

## Tree Search to find all states
Note: we are finding all states given that player 1 (white) starts playing. 
States of player 2 are expressed in cannonical form. 

In [3]:
n = 4
game = Game(n)
board = game.getInitBoard()

In [4]:
# Find all states of game doing a search tree if player 1 starts
first_player = 1
%time states_actions_player_1 = bfs_cannonical(game, board, first_player) # (1 white)

CPU times: user 56.6 s, sys: 469 ms, total: 57.1 s
Wall time: 57.9 s


In [9]:
# Find all states of game doing a search tree if player 2 starts
first_player = -1
%time states_actions_player_2 = bfs_cannonical(game, board, first_player) #(-1 black)

CPU times: user 1min, sys: 785 ms, total: 1min 1s
Wall time: 1min 4s


In [10]:
states_actions = {**states_actions_player_1, **states_actions_player_2}

In [11]:
print('Number of states:', len(states_actions_player_1))
print('Number of states:', len(states_actions_player_2))

Number of states: 53651
Number of states: 53651


In [12]:
print('Number of states:', len(states_actions))

Number of states: 91282


In [13]:
np.save('states_actions', states_actions)

In [14]:
# Size of the file. Only works if linux or mac. Try dir for windows
! ls -lah states_actions.npy

-rw-r--r--  1 julianganzabal  staff   144M Feb 24 17:40 states_actions.npy


In [15]:
state = list(states_actions.keys())[0]
print('Example of state:')
print(state)
print()
print('Actions, rewards and next nodes of state:')
for k, v in states_actions[state].items():
    print(k, v)

Example of state:
(0, 0, 0, 0, 0, -1, 1, 0, 0, 1, -1, 0, 0, 0, 0, 0)

Actions, rewards and next nodes of state:
1 {'winner': 0, 'next_node': (0, -1, 0, 0, 0, -1, -1, 0, 0, -1, 1, 0, 0, 0, 0, 0)}
4 {'winner': 0, 'next_node': (0, 0, 0, 0, -1, -1, -1, 0, 0, -1, 1, 0, 0, 0, 0, 0)}
11 {'winner': 0, 'next_node': (0, 0, 0, 0, 0, 1, -1, 0, 0, -1, -1, -1, 0, 0, 0, 0)}
14 {'winner': 0, 'next_node': (0, 0, 0, 0, 0, 1, -1, 0, 0, -1, -1, 0, 0, 0, -1, 0)}


### Questions:

In [16]:
# Board after player 1 plays action 1
board_1 = np.array(
[[0,  1,  0,  0],
[ 0,  1,  1,  0],
[ 0,  1, -1,  0],
[ 0,  0,  0,  0]])
states_actions[tuple(board_1.reshape(-1))]

KeyError: (0, 1, 0, 0, 0, 1, 1, 0, 0, 1, -1, 0, 0, 0, 0, 0)

why the above is not a valid state? Which is the state for the Board after player 1 plays action 1?

## Generate a uniform stochastic policy
It is used as initial policy to test stochastic policy evalution 

In [17]:
from dynamic_programming import generate_uniform_stochastic_policy
pi = generate_uniform_stochastic_policy(states_actions)

for i in range(2):
    state = list(pi.keys())[i]
    print('Example of state:')
    print(state)
    print('Actions, Probabilities:')
    for k, v in pi[state].items():
        print(k, v)
    print('------------------')

Example of state:
(0, 0, 0, 0, 0, -1, 1, 0, 0, 1, -1, 0, 0, 0, 0, 0)
Actions, Probabilities:
1 0.25
4 0.25
11 0.25
14 0.25
------------------
Example of state:
(0, -1, 0, 0, 0, -1, -1, 0, 0, -1, 1, 0, 0, 0, 0, 0)
Actions, Probabilities:
0 0.3333333333333333
2 0.3333333333333333
8 0.3333333333333333
------------------


## Policy evaluation test
### Stochastic policy evaluation

In [18]:
from dynamic_programming import policy_evaluation, stochastic_policy_eval_step
# stochastic_policy_eval_step does policy_evaluation using probabilities. Check library

In [21]:
# Run it multiple times to check it takes different number of iterations to converge
stochastic_pi = generate_uniform_stochastic_policy(states_actions)
V_stochastic, iters = policy_evaluation(stochastic_policy_eval_step, 
                             states_actions, 
                             stochastic_pi, 1e-8, verbose=1)

Iteration number:  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 


In [22]:
print('10 examples of Value function:')
i = 0 
for k, v in V_stochastic.items():
    print(k, v)
    if i == 10:
        break
    i += 1

10 examples of Value function:
(0, 0, 0, 0, 0, -1, 1, 0, 0, 1, -1, 0, 0, 0, 0, 0) -0.19926756827206293
(0, -1, 0, 0, 0, -1, -1, 0, 0, -1, 1, 0, 0, 0, 0, 0) 0.19926756827206293
(0, 0, 0, 0, -1, -1, -1, 0, 0, -1, 1, 0, 0, 0, 0, 0) 0.19926756827206293
(0, 0, 0, 0, 0, 1, -1, 0, 0, -1, -1, -1, 0, 0, 0, 0) 0.1992675682720629
(0, 0, 0, 0, 0, 1, -1, 0, 0, -1, -1, 0, 0, 0, -1, 0) 0.19926756827206293
(-1, 1, 0, 0, 0, -1, 1, 0, 0, 1, -1, 0, 0, 0, 0, 0) -0.7334317552457347
(0, 1, -1, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0, 0, 0, 0) 0.10847170895012459
(0, 1, 0, 0, 0, 1, 1, 0, -1, -1, -1, 0, 0, 0, 0, 0) 0.027157341479421185
(-1, 0, 0, 0, 1, -1, 1, 0, 0, 1, -1, 0, 0, 0, 0, 0) -0.7334317552457347
(0, 0, -1, 0, 1, 1, -1, 0, 0, 1, -1, 0, 0, 0, 0, 0) 0.027157341479421192
(0, 0, 0, 0, 1, 1, 1, 0, -1, -1, -1, 0, 0, 0, 0, 0) 0.10847170895012459


### Deterministic policy evaluation

In [23]:
from dynamic_programming import generate_deterministic_policy, deterministic_policy_eval_step

In [24]:
deterministic_pi = generate_deterministic_policy(states_actions)
for i in range(2):
    state = list(pi.keys())[i]
    print('Example of state:', state)
    print('"best" action:', deterministic_pi[state])
    print('------------------')

Example of state: (0, 0, 0, 0, 0, -1, 1, 0, 0, 1, -1, 0, 0, 0, 0, 0)
"best" action: 11
------------------
Example of state: (0, -1, 0, 0, 0, -1, -1, 0, 0, -1, 1, 0, 0, 0, 0, 0)
"best" action: 0
------------------


In [25]:
# Run it multiple times to check it always takes the same number of iterations
V_deterministic, iters = policy_evaluation(deterministic_policy_eval_step, 
                             states_actions, 
                             deterministic_pi, 1e-8, verbose=1)

Iteration number:  1 2 3 4 5 6 7 8 9 10 11 12 13 14 


In [26]:
print('10 examples of Value function:')
i = 0 
for k, v in V_deterministic.items():
    print(k, v)
    if i == 10:
        break
    i += 1

10 examples of Value function:
(0, 0, 0, 0, 0, -1, 1, 0, 0, 1, -1, 0, 0, 0, 0, 0) -1
(0, -1, 0, 0, 0, -1, -1, 0, 0, -1, 1, 0, 0, 0, 0, 0) 1
(0, 0, 0, 0, -1, -1, -1, 0, 0, -1, 1, 0, 0, 0, 0, 0) 1
(0, 0, 0, 0, 0, 1, -1, 0, 0, -1, -1, -1, 0, 0, 0, 0) 1
(0, 0, 0, 0, 0, 1, -1, 0, 0, -1, -1, 0, 0, 0, -1, 0) 1
(-1, 1, 0, 0, 0, -1, 1, 0, 0, 1, -1, 0, 0, 0, 0, 0) -1
(0, 1, -1, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0, 0, 0, 0) -1e-06
(0, 1, 0, 0, 0, 1, 1, 0, -1, -1, -1, 0, 0, 0, 0, 0) -1
(-1, 0, 0, 0, 1, -1, 1, 0, 0, 1, -1, 0, 0, 0, 0, 0) -1
(0, 0, -1, 0, 1, 1, -1, 0, 0, 1, -1, 0, 0, 0, 0, 0) 1
(0, 0, 0, 0, 1, 1, 1, 0, -1, -1, -1, 0, 0, 0, 0, 0) 1


See values are just 1 or -1 (They could be +-0.2 for ties)

## Policy Improve

In [29]:
from dynamic_programming import policy_improve, policy_iteration

In [30]:
initial_policy = generate_deterministic_policy(states_actions)
optimum_policy, optimum_V = policy_iteration(states_actions, initial_policy, verbose = 1)

Iteration number:  1 2 3 4 5 6 7 8 9 10 11 12 13 14 
Number of differences of new policy vs old policy: 23282
---------------------------
Iteration number:  1 2 3 4 5 6 7 8 9 10 11 12 13 
Number of differences of new policy vs old policy: 4189
---------------------------
Iteration number:  1 2 3 4 5 6 7 8 9 10 11 12 13 14 
Number of differences of new policy vs old policy: 1182
---------------------------
Iteration number:  1 2 3 4 5 6 7 8 9 10 11 12 13 
Number of differences of new policy vs old policy: 299
---------------------------
Iteration number:  1 2 3 4 5 6 7 8 9 10 11 12 13 14 
Number of differences of new policy vs old policy: 83
---------------------------
Iteration number:  1 2 3 4 5 6 7 8 9 10 11 12 13 
Number of differences of new policy vs old policy: 22
---------------------------
Iteration number:  1 2 3 4 5 6 7 8 9 10 11 12 13 
Number of differences of new policy vs old policy: 6
---------------------------
Iteration number:  1 2 3 4 5 6 7 8 9 10 11 12 13 
Number of 

In [31]:
n = 4
game = Game(n)
board = game.getInitBoard()
player = 1
print(board)

[[ 0  0  0  0]
 [ 0 -1  1  0]
 [ 0  1 -1  0]
 [ 0  0  0  0]]


In [32]:
# Empieza player_1
first_player = 1
print(optimum_V[tuple(first_player * board.reshape(-1))])

-1


The above result indicates that player 1 always looses

In [33]:
# Empieza player_2
first_player = -1
print(optimum_V[tuple(first_player * board.reshape(-1))])

-1


In [34]:
np.save('Value_func_only_winner', optimum_V)

In [35]:
np.save('pi_func_only_winner', optimum_policy)

In [39]:
! ls -lah *.npy

-rw-r--r--  1 julianganzabal  staff    81M Feb 24 11:47 Value_func_diff_reward.npy
-rw-r--r--  1 julianganzabal  staff    76M Feb 24 17:45 Value_func_only_winner.npy
-rw-r--r--  1 julianganzabal  staff    81M Feb 24 11:47 pi_func_diff_reward.npy
-rw-r--r--  1 julianganzabal  staff    80M Feb 24 17:45 pi_func_only_winner.npy
-rw-r--r--  1 julianganzabal  staff   144M Feb 24 17:40 states_actions.npy


# Lets play game with optimun policy

In [1]:
from othello.OthelloGame import OthelloGame as Game
from othello.OthelloGame import display as displayGame
from matplotlib import pyplot as plt
from matplotlib import patches
import numpy as np

from playing_stats import EvaluatePolicy

In [2]:
optimum_policy = np.load('pi_func_only_winner.npy').item()

In [3]:
evalPolicy = EvaluatePolicy(optimum_policy)

In [4]:
n = 4
game = Game(n)
board = game.getInitBoard()
player = 1

# Random vs Random as and Greedy vs Greedy as reference

In [8]:
def display_results(player_1_wins, player_2_wins, ties, margins, steps_array, pieces):
    print('player_1 wins:', str(int(100*player_1_wins/episodes + 0.5)) + '%')
    print('player_2 wins:', str(int(100*player_2_wins/episodes + 0.5)) +'%')
    print('ties:', str(int(100*ties/episodes + 0.5))+ '%')
    print('Max, Mean, Min margins: ', end ='')
    print(np.max(margins), np.mean(margins), np.min(margins))
    print('Max, Mean, Min steps: ', end ='')
    print(np.max(steps_array), np.mean(steps_array), np.min(steps_array))
    print('Max, Mean, Min pieces: ', end ='')
    print(np.max(pieces), np.mean(pieces), np.min(pieces))

In [9]:
episodes = 1000
player_1_wins, player_2_wins, ties, margins, steps_array, pieces = evalPolicy.get_stats(game, 
                                                board, 
                                                {1: evalPolicy.random_player, -1: evalPolicy.random_player}, 
                                                episodes)
display_results(player_1_wins, player_2_wins, ties, margins, steps_array, pieces)

player_1 wins: 39%
player_2 wins: 52%
ties: 9%
Max, Mean, Min margins: 16 -1.106 -16
Max, Mean, Min steps: 16 12.541 7
Max, Mean, Min pieces: 16 15.784 10


Second player seems to have more probability to win playing random

In [10]:
episodes = 1000
player_1_wins, player_2_wins, ties, margins, steps_array, pieces = evalPolicy.get_stats(game, 
                                                board, 
                                                {1: evalPolicy.greedy_player, -1: evalPolicy.greedy_player}, 
                                                episodes)
display_results(player_1_wins, player_2_wins, ties, margins, steps_array, pieces)

player_1 wins: 41%
player_2 wins: 52%
ties: 7%
Max, Mean, Min margins: 15 -0.696 -16
Max, Mean, Min steps: 15 12.233 7
Max, Mean, Min pieces: 16 15.538 10


## Policy plays second against random

In [11]:
episodes = 1000
player_1_wins, player_2_wins, ties, margins, steps_array, pieces = evalPolicy.get_stats(game, 
                                                board, 
                                                {1: evalPolicy.random_player, -1: evalPolicy.policy_player}, 
                                                episodes)
display_results(player_1_wins, player_2_wins, ties, margins, steps_array, pieces)

player_1 wins: 0%
player_2 wins: 100%
ties: 0%
Max, Mean, Min margins: -2 -6.957 -16
Max, Mean, Min steps: 14 12.678 10
Max, Mean, Min pieces: 16 15.843 13


Optimal policy always win as second player

## Policy plays first against random

In [12]:
episodes = 1000
player_1_wins, player_2_wins, ties, margins, steps_array, pieces = evalPolicy.get_stats(game, 
                                                board, 
                                                {1: evalPolicy.policy_player, -1: evalPolicy.random_player}, 
                                                episodes)
display_results(player_1_wins, player_2_wins, ties, margins, steps_array, pieces)

player_1 wins: 83%
player_2 wins: 18%
ties: 0%
Max, Mean, Min margins: 14 3.154 -9
Max, Mean, Min steps: 14 11.654 9
Max, Mean, Min pieces: 16 15.188 12


Obtimal policy can't win all but does much better than random player 1

## Policy plays first against greedy

In [13]:
episodes = 1000
player_1_wins, player_2_wins, ties, margins, steps_array, pieces = evalPolicy.get_stats(game, 
                                                board, 
                                                {1: evalPolicy.policy_player, -1: evalPolicy.greedy_player}, 
                                                episodes)
display_results(player_1_wins, player_2_wins, ties, margins, steps_array, pieces)

player_1 wins: 68%
player_2 wins: 32%
ties: 0%
Max, Mean, Min margins: 14 2.795 -9
Max, Mean, Min steps: 14 11.724 9
Max, Mean, Min pieces: 16 15.139 12


Also does good as player 1 against greedy